# Generated by Django 6.0.5 on 2026-06-05 21:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='oficio_prefeitura',
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='documento_meio_ambiente',
            field=models.FileField(blank=True, null=True, upload_to='documentos/meio_ambiente/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='documento_sanitario',
            field=models.FileField(blank=True, null=True, upload_to='documentos/sanitario/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
